{% set name = "types-colorama" %}
{% set version = "0.4.14" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-colorama-{{ version }}.tar.gz
  sha256: 99a926d9a608c380da3a066f832ae9c608d8dd52a62041c8329a821d79b4d6af

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/colorama-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for colorama
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
