{% set name = "types-colorama" %}
{% set version = "0.4.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-colorama-{{ version }}.tar.gz
  sha256: 474fc6b0ed83cd341189ac6f78b93393dfd6b61800a82ddf4fc2032f4700b4e7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/colorama-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for colorama
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
